spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CouponSystem?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#  kafka:
#    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
#    consumer:
#      group-id: coupon_system
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      max-poll-records: 100
#    properties:
#      spring.json.trusted.packages: '*'

#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: UTC

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        use_sql_comments: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.example.file_test: debug

server:
  port: 8081
